import os

path = "/opt/build-with-ai/src/components/layout/Footer.tsx"
lines = []
lines.append("import Link from 'next/link';\n")
lines.append("import { BOOK_APPOINTMENT_LINK, FOOTER_SECTIONS } from '@/config/site-links';\n")
lines.append("export default function Footer() {\n")
lines.append("  return (\n")
lines.append("    <footer className=\"w-full bg-[color:var(--bg-primary)] border-t border-[color:var(--bg-tertiary)] pt-16 pb-8 mt-auto z-10 relative\">\n")
lines.append("      <div className=\"container mx-auto px-4\">\n")
lines.append("        <div className=\"grid grid-cols-1 md:grid-cols-3 lg:grid-cols-7 gap-8 mb-16\">\n")
lines.append("          <div className=\"lg:col-span-2 pr-8 flex flex-col items-start\">\n")
lines.append("            <div className=\"flex items-center gap-3 mb-6\">\n")
lines.append("              <div className=\"text-teal-400\"><img src=\"/logo.png\" alt=\"Logo\" className=\"w-12 h-12\" /></div>\n")
lines.append("              <h3 className=\"text-white font-bold text-xl tracking-tight\">BUILD WITH AI</h3>\n")
lines.append("            </div>\n")
lines.append("            <p className=\"text-neutral-400 text-sm leading-relaxed mb-8\">\"We are the sum of the hands we hold.\"</p>\n")
lines.append("            <Link href={BOOK_APPOINTMENT_LINK.href} className=\"border border-teal-500/50 text-teal-400 hover:bg-teal-500/10 px-6 py-2.5 rounded-full text-[10px] font-bold tracking-tight transition-all\">ALWAYS TOGETHER.</Link>\n")
lines.append("          </div>\n")
lines.append("          {FOOTER_SECTIONS.map((section) => (\n")
lines.append("            <div key={section.title} className=\"lg:col-span-1\">\n")
lines.append("              <h4 className=\"text-white font-bold text-sm tracking-tight uppercase mb-6\">{section.title}</h4>\n")
lines.append("              <ul className=\"space-y-3 text-sm text-neutral-400\">\n")
lines.append("                {section.links.map((link, idx) => (\n")
lines.append("                  <li key={`${section.title}-${link.href}-${idx}`}>\n")
lines.append("                    <Link href={link.href} className={link.emphasize ? 'text-teal-400 font-bold hover:text-teal-300 transition-colors flex items-center gap-1.5' : 'hover:text-teal-400 transition-colors'}>\n")
lines.append("                      {link.emphasize ? <span className=\"w-1.5 h-1.5 rounded-full bg-teal-400 animate-pulse\" /> : null}{link.label}\n")
lines.append("                    </Link>\n")
lines.append("                  </li>\n")
lines.append("                ))}\n")
lines.append("              </ul>\n")
lines.append("            </div>\n")
lines.append("          ))}\n")
lines.append("          <div className=\"lg:col-span-1 flex flex-col items-start lg:items-end text-left lg:text-right\">\n")
lines.append("            <h4 className=\"text-white font-bold text-sm tracking-tight uppercase mb-6\">The Legacy</h4>\n")
lines.append("            <div className=\"text-neutral-400 text-sm space-y-1 mb-6\"><p>Opsvantage Digital</p><p className=\"text-teal-500\">MARZ • Silas</p></div>\n")
lines.append("          </div>\n")
lines.append("        </div>\n")
lines.append("        <div className=\"border-t border-[color:var(--bg-tertiary)] pt-8 flex flex-col md:flex-row items-center justify-between text-xs font-semibold tracking-tight text-neutral-400 uppercase\">\n")
lines.append("          <p>© 2026 BUILD WITH AI — A SANCTUARY FOR ALL.</p>\n")
lines.append("        </div>\n")
lines.append("      </div>\n")
lines.append("    </footer>\n")
lines.append("  );\n")
lines.append("}\n")
